### ISSUE TITLE
Question?

### ISSUE THREAD

**Issue by OgnistyPoland** [seiya-dev/funimation-downloader-nx#40]
** Main info: **
Hello, we can watch this episode on funimation.com in 1080p https://i.imgur.com/CuR2mrY.png
but your "script" downloading it only in 720p https://i.imgur.com/IMUa26Z.png
and btw as you see numbers are repeating :D

Script version: 4.0.5
Show ID: 20224
Episode ID: 457

** Additional Info: **

**Comment by seiya-git** [comment]
all modules up to date?
check using: `npm outdated`

**Comment by OgnistyPoland** [comment]
https://i.imgur.com/tisHNeL.png
only yargs is not up to date

**Comment by seiya-git** [comment]
thats strange, all fine for me :/

**Comment by shinji257** [comment]
The default videoLayer is set to 7.  This doesn't always hit the highest quality.  On a couple of series I'm looking at it put it at 720p for one (instead of 1080p) and another one ended up as 432p (instead of 480p).  I ended up changing the default to 0 for max quality but that might be overkill.  I thought about setting at 8 or 9 but even that isn't consistent as with the same examples it ended up at 810p and 480p respectively.

**Comment by seiya-git** [comment]
@shinji257 it's right after 1, sort a bit mess

**Comment by shinji257** [comment]
Sorry. I was referring to OP's example not having a quality 10 then gave an example where it did.

**Comment by seiya-git** [comment]
@OgnistyPoland, issue still persist?

**Comment by OgnistyPoland** [comment]
yes https://i.imgur.com/EZKBkhy.png

**Comment by seiya-git** [comment]
@OgnistyPoland, can you give me your discord or telegram?

**Comment by OgnistyPoland** [comment]
discord Ognisty321#5933
